server:
  servlet:
    context-path: /jtradebot-advance-processor
  port: 8084

spring:
  timezone: Asia/Kolkata
  profiles:
    active: local
  application:
    name: jtradebot-advance-processor
  kafka:
    bootstrap-servers: pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='QVHT6GTXZNDX2H4R' password='mkg7xHLzmOZy3hOhBSCUU+q2Bxx7JleWeHS35qwxZlk2rVhkWbcxik+AhZzkxkU3';
      session.timeout.ms: 45000
  data:
    mongodb:
      uri: mongodb+srv://jtradebotuser:ByQMNv50k6wWZDXj@jtradebot-prod.joexsjf.mongodb.net/jtradebot?retryWrites=true&w=majority&appName=jtradebot-prod
      database: jtradebot
      auto-index-creation: true

aws:
  region: ap-south-1
  kite:
    secret-name: kite_connect
    api-key: KITE_API_KEY_ADVANCED
    api-secret: KITE_API_SECRET_ADVANCED
    basic-auth-username: APP_BASIC_AUTH_USERNAME
    basic-auth-password: APP_BASIC_AUTH_PASSWORD
  sqs:
    queue-url: https://sqs.ap-south-1.amazonaws.com/644885005419/liveTickProcessor.fifo
    region: ap-south-1
  sns:
    topic-arn: arn:aws:sns:ap-south-1:692859939395:jtradebot-notifications

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - loggers
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true


logging:
  level:
    com.jtradebot.processor.service.TickProcessService: DEBUG
    com.jtradebot.processor.service.impl.IndicatorFlattenerServiceImpl: INFO
    com.jtradebot.processor.service.impl.ScalpingEntryServiceImpl: INFO
    com.jtradebot.processor.service.impl.DynamicIndicatorFlattenerServiceImpl: INFO
    com.jtradebot.processor.service.impl.ScalpingVolumeSurgeServiceImpl: INFO
  
  # Backtest Data Collection Configuration
  backtest-data:
    enabled: false  # Enable/disable automatic data collection
    batch-size: 100  # Number of data points to collect before writing to file
    batch-interval-ms: 5000  # Maximum time to wait before writing batch (5 seconds)
    output-directory: "./backtest-data"  # Directory to store data files
    session-prefix: "auto_session"  # Prefix for automatic session IDs
    max-file-size-mb: 50  # Maximum file size before creating new file
    ticks-per-file: 1000  # Number of ticks to store in each JSON file
