spring:
  kafka:
    consumer:
      topic: jtradebot-backtest-ticks
  data:
    mongodb:
      uri: mongodb://root:pass@localhost:27017/jtradebot?authSource=admin

logging:
  level:
    root: INFO
    org:
      mongodb:
        driver: INFO

# Balance Check Configuration
balance-check:
  scheduler:
    enabled: false  # Enable/disable automatic balance checking via scheduler
