package com.jtradebot.processor.model.enums;

public enum ExitReasonEnum {
    INDEX_STOPLOSS_HIT,
    INDEX_TARGET_HIT,
    STOPLOSS_HIT,
    TRAILING_STOPLOSS_HIT,
    TARGET_HIT,
    EXIT_SIGNAL,
    TIME_BASED_EXIT,
    MAX_DAY_LOSS_REACHED,
    BAD_ENTRY,
    MAX_DAY_PROFIT_REACHED,
    MAX_POINTS_PER_DAY_REACHED,
    FORCE_EXIT,
    MARKET_END_CLOSURE,
    PRICE_MOVEMENT_EXIT
}
